[package]
name = "tvmaze-rs"
version = "0.1.0"
authors = ["Jason Chen <jason@jcndrop.com>"]

[dependencies]
futures = "0.1"
http = "0.1.5"
hyper = { git = "https://github.com/hyperium/hyper" }
serde = "1.0.17"
serde_derive = "1.0.17"
serde_json = "1.0.17"
tokio = "0.1.5"
url = "1.7.0"
